version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - teletyperacer

  client:
    build:
      context: ./client
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - teletyperacer

networks:
  teletyperacer:
    driver: bridge